// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ec6eDCAGMjbYThvQYa0jockqCXaOGKc',
    appId: '1:731400089356:web:09fa1ce75360495863a329',
    messagingSenderId: '731400089356',
    projectId: 'authen-app-13',
    authDomain: 'authen-app-13.firebaseapp.com',
    storageBucket: 'authen-app-13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA96LMo4k5DIeAaFfIt0hSbNNadqAhzqZA',
    appId: '1:731400089356:android:4044686a559d538f63a329',
    messagingSenderId: '731400089356',
    projectId: 'authen-app-13',
    storageBucket: 'authen-app-13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg1s04AhhI-GPAuHKg1FtxToSsGWw-V-Y',
    appId: '1:731400089356:ios:20c37029c81bcc3163a329',
    messagingSenderId: '731400089356',
    projectId: 'authen-app-13',
    storageBucket: 'authen-app-13.firebasestorage.app',
    iosBundleId: 'com.example.authApp13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg1s04AhhI-GPAuHKg1FtxToSsGWw-V-Y',
    appId: '1:731400089356:ios:20c37029c81bcc3163a329',
    messagingSenderId: '731400089356',
    projectId: 'authen-app-13',
    storageBucket: 'authen-app-13.firebasestorage.app',
    iosBundleId: 'com.example.authApp13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-ec6eDCAGMjbYThvQYa0jockqCXaOGKc',
    appId: '1:731400089356:web:9355b19480f1a9c563a329',
    messagingSenderId: '731400089356',
    projectId: 'authen-app-13',
    authDomain: 'authen-app-13.firebaseapp.com',
    storageBucket: 'authen-app-13.firebasestorage.app',
  );
}
